image: markhobson/maven-chrome:jdk-11

stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn compile

smokesuite:
  stage: test
  script:
    - mvn test -Dsuite=smoke -Denvironment=qa

regressionsuite:
  stage: test
  script:
    - mvn test -Dsuite=regression -Denvironment=stage
