image: markhobson/maven-chrome:jdk-11
pipelines:
  branches:
    master:
      - step:
          name: "Build"
          caches:
            - maven
          script:
            - mvn clean
          artifacts:
            - build/**

      - parallel:
          - step:
              name: "Smoke Suite"
              caches:
                - maven
              script:
                - mvn clean test -Dsuite=smoke -Denvironment=qa
          - step:
              name: "Regression Suite"
              caches:
                - maven
              script:
                - mvn clean test -Dsuite=regression -Denvironment=qa