image: markhobson/maven-chrome:jdk-11
pipelines:
  branches:
    master:
      - step:
          name: "Build"
          caches:
            - maven
          script:
            - mvn clean
          artifacts:
            - build/**

      - parallel:
          - step:
              name: "Smoke Suite"
              caches:
                - maven
              script:
                - mvn clean test -Dsuite=smoke -Denvironment=qa
          - step:
              name: "Regression Suite"
              caches:
                - maven
                - .m2/repository/
                - target/
              script:
                - mvn clean test -Dsuite=regression -Denvironment=qa
          - step:
              name: "Full Suite"
              caches:
                - maven
              script:
                - mvn clean test -Dsuite=full -Denvironment=stage

definitions:
  services:
    selenium-hub:
      image: selenium/hub:latest
      container_name: selenium-hub
      ports:
        - "4444:4444"

    firefoxnodeone:
      image: selenium/node-firefox:latest
      volumes:
        - /dev/shm:/dev/shm
      depends_on:
        - selenium-hub
      environment:
        - HUB_HOST=selenium-hub
        - HUB_PORT=4444

    chromenodeone:
      image: selenium/node-chrome:latest
      volumes:
        - /dev/shm:/dev/shm
      depends_on:
        - selenium-hub
      environment:
        - HUB_HOST=selenium-hub
        - HUB_PORT=4444
