image: markhobson/maven-chrome:jdk-11
pipelines:
  branches:
    master:
      - step:
          name: "Build"
          caches:
            - maven
          script:
            - mvn clean
          artifacts:
            - build/**

      - parallel:
          - step:
              name: "Smoke Suite"
              caches:
                - maven
              script:
                - mvn clean test -Dsuite=smoke -Denvironment=qa
          - step:
              name: "Regression Suite"
              caches:
                - maven
              script:
                - mvn clean test -Dsuite=regression -Denvironment=qa
          - step:
              name: "Full Suite"
              caches:
                - maven
              services:
                - selenium-hub
                - chromenodeone
                - firefoxnodeone
              script:
                - mvn clean test -Dsuite=full -Denvironment=stage

definitions:
  services:
    selenium-hub:
      image: selenium/hub:latest


    firefoxnodeone:
      image: selenium/node-firefox:3.141.59
      environment:
        HUB_PORT_4444_TCP_ADDR: 127.0.0.1
        HUB_PORT_4444_TCP_PORT: "4444"

    chromenodeone:
      image: selenium/node-chrome:3.141.5
      environment:
        HUB_PORT_4444_TCP_ADDR: 127.0.0.1
        HUB_PORT_4444_TCP_PORT: "4444"