image: markhobson/maven-chrome:jdk-11

pipelines:
  default:
    - step:
        caches:
          - .m2/repository/
          - target/
        script: # Modify the commands below to build your repository.
          - mvn clean test -Dsuite=smoke -Denvironment=qa # -B batch mode makes Maven less verbose